# Create a post 
POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Planet Mercury",
    "content": "Mercury is the closest planet to the sun.",
    "category": "planet",
    "tags": ["planet", "solar system"]
  
}

### GET
GET http://localhost:3000/posts/15abf200-037c-4ae5-8abc-c704ed788edd

###
GET http://localhost:3000/posts?term=video


### UPDATE
PUT http://localhost:3000/posts/15abf200-037c-4ae5-8abc-c704ed788edd
Content-Type: application/json

{
  "title": "Who am i?",
  "content": "My name is jaylen rojas serranos."
}


### DELETE

DELETE http://localhost:3000/posts/44262047-8446-4b2c-b143-73a88a827710