# Create a post 
POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Naruto Shippuden",
  "content": "Naruto Shippuden is a Japanese anime series based on Masashi Kishimoto's manga series.",
  "category": "anime",
  "tags": ["anime", "action", "adventure"]
}

### GET ALL POSTS
GET http://localhost:3000/posts
### GET SINGLE POST
GET http://localhost:3000/posts/44dcaa91-2a03-11f0-b1cb-346f24a41da4
### UPDATE
PUT http://localhost:3000/posts/44dcaa91-2a03-11f0-b1cb-346f24a41da4
Content-Type: application/json

{
  "title": "Amazings things about NodeJS",
  "category": "productivity"
}
### DELETE POSTS
DELETE http://localhost:3000/posts/11111111-1111-1111-1111-111111111111